@url = http://localhost:8080/api

GET {{url}}/shop
Accept: application/json

###
GET {{url}}/shop/4
Accept: application/json

###
POST {{url}}/shop
Content-Type: application/json
Accept: application/json

{
  "name": "John Doete25441",
  "address": "1241 Main St",
  "phone": "566-555-5555",
  "email": "testjohn1234@test.com"
}

###
PUT {{url}}/shop
Content-Type: application/json
Accept: application/json

{
    "id": 7,
    "name": "John Doesn",
    "email": "testjohn2@test.com",
    "address": "124 Main St",
    "phone": "556-555-5555"
}

###
DELETE {{url}}/shop/7

###
GET {{url}}/barista
Accept: application/json

###
POST {{url}}/barista
Content-Type: application/json

{
  "name": "John Does109",
  "email": "testjohns1011@test.com",
  "shopId": 4
}

###
PUT {{url}}/barista
Content-Type: application/json
Accept: application/json

{
  "id": 10,
  "name": "John Does",
  "email": "testjohns242@test.com",
  "shopId": 4
}

###
DELETE {{url}}/barista/10