services:
  postgres:
    image: 'postgres:latest'
    command:
      - 'postgres'
      - '-c'
      - 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      - 'POSTGRES_DB=appdb'
      - 'POSTGRES_PASSWORD=S@ecret123'
      - 'POSTGRES_USER=appuser'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - '5432:5432'
    volumes:
      - type: 'bind'
        source: './db/postgresql.conf'
        target: '/etc/postgresql/postgresql.conf'
  memcached:
    image: 'memcached:latest'
    container_name: 'memcached'
    environment:
      - MEMCACHED_MAX_MEMORY=64m
      - MEMCACHED_THREADS=4
    ports:
      - '11211:11211'
  tempo-init:
    image: 'grafana/tempo:latest'
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./ops/tempo-data:/var/tempo
  tempo:
    image: 'grafana/tempo:latest'
    container_name: 'tempo'
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./ops/tempo.yaml:/etc/tempo.yaml
      - ./ops/tempo-data:/var/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    depends_on:
      - tempo-init
      - memcached
  prometheus:
    image: prom/prometheus:latest
    container_name: 'prometheus'
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./ops/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
  grafana:
    image: 'grafana/grafana:latest'
    container_name: 'grafana'
    volumes:
      - ./ops/grafana:/etc/grafana/provisioning/datasources
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-traces-app
    ports:
      - "3000:3000"