services:
  postgres:
    image: 'postgres:latest'
    command:
      - 'postgres'
      - '-c'
      - 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      - 'POSTGRES_DB=appdb'
      - 'POSTGRES_PASSWORD=S@ecret123'
      - 'POSTGRES_USER=appuser'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - '5432:5432'
    volumes:
      - type: 'bind'
        source: './db/postgresql.conf'
        target: '/etc/postgresql/postgresql.conf'