INSERT INTO barista (name, email, shop_id) values ('Barista 1', 'barista1@temp.com', 1);
INSERT INTO barista (name, email, shop_id) values ('Barista 2', 'barista1@temp.com', 1);
INSERT INTO barista (name, email, shop_id) values ('Barista 3', 'barista1@temp.com', 2);
INSERT INTO barista (name, email, shop_id) values ('Barista 4', 'barista1@temp.com', 3);
INSERT INTO barista (name, email, shop_id) values ('Barista 4', 'barista1@temp.com', 3);
INSERT INTO barista (name, email, shop_id) values ('Barista 5', 'barista1@temp.com', 4);
INSERT INTO barista (name, email, shop_id) values ('Barista 6', 'barista1@temp.com', 4);
INSERT INTO barista (name, email, shop_id) values ('Barista 7', 'barista1@temp.com', 4);
INSERT INTO barista (name, email, shop_id) values ('Barista 8', 'barista1@temp.com', 4);