spring:
  threads:
    virtual:
      enabled: true
  application:
    name: cafe
  lifecycle:
    timeout-per-shutdown-phase: 20s
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: S@ecret123
    hikari:
      schema: cafe
      auto-commit: true
  flyway:
    enabled: true
    locations: classpath:db
    create-schemas: true
    schemas: cafe
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
        schema: cafe
      externalization:
        enabled: false
      republish-outstanding-events-on-restart: true
      completion-mode: update
    detection-strategy: explicitly-annotated
  docker:
    compose:
      lifecycle-management: START_AND_STOP
management:
  server:
    port: 9990
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-components: always
      show-details: always
    prometheus:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"
  otlp:
    logging:
      endpoint: http://localhost:3100/otlp
      transport: http
      export:
        enabled: true
    tracing:
      endpoint: http://localhost:4317/v1/traces
      transport: grpc
      compression: none
    metrics:
      export:
        url: http://localhost:9090/api/v1/otlp/v1/metrics
        enabled: true
        step: 15s
        read-timeout: 10s
        connect-timeout: 10s
        headers:
          source: otlp
server:
  port: 8080
logging:
  pattern:
    dateformat: dd-MMM-yyyy'T'HH:mm:ss.SSS
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  include-application-name: false
