spring:
  threads:
    virtual:
      enabled: true
  application:
    name: cafe
  lifecycle:
    timeout-per-shutdown-phase: 20s
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: S@ecret123
    hikari:
      schema: cafe
      auto-commit: true
  flyway:
    enabled: on
    locations: classpath:db
    create-schemas: on
    schemas: cafe
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: on
        schema: cafe
      externalization:
        enabled: false
      republish-outstanding-events-on-restart: true
      completion-mode: update
  docker:
    compose:
      lifecycle-management: start_and_stop
management:
  server:
    port: 8082
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-components: always
      show-details: always
    prometheus:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"
  otlp:
    tracing:
      endpoint: http://localhost:4317/v1/traces
      transport: grpc
      compression: none
server:
  port: 8080
logging:
  pattern:
    dateformat: dd-MMM-yyyy'T'HH:mm:ss.SSS
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  include-application-name: false